version: '1.0.1'

services:
  web:
    build:
      dockerfile: Dockerfile
      context: .
      target: development
    ports:
      - "8001:8001"
    networks:
      - mongors-network
    env_file:
      - .env
    command: npm run start:dev

networks:
  mongors-network:
    external: true
