version: "3.9"

services:
  postgres-credit:
    image: postgres:15
    container_name: postgres-credit
    environment:
      POSTGRES_DB: credit_service_db
      POSTGRES_USER: creditService
      POSTGRES_PASSWORD: creditService

  postgres-user:
    image: postgres:15
    container_name: postgres-user
    environment:
      POSTGRES_DB: user_service_db
      POSTGRES_USER: userService
      POSTGRES_PASSWORD: userService

  postgres-keycloak:
    image: postgres:15
    container_name: postgres-keycloak
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password

  keycloak:
    image: quay.io/keycloak/keycloak:21.0.2
    container_name: keycloak
    command: [ "start-dev", "--import-realm" ]
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres-keycloak
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_SCHEMA: public
      DB_PASSWORD: password
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    volumes:
      - ./realm/:/opt/keycloak/data/import/
    ports:
      - "8181:8080"
    expose:
      - "8181"
    depends_on:
      - postgres-keycloak

  discovery-server:
    build: discovery-server
    container_name: discovery-server
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - keycloak
    expose:
      - "8761"

  auth_server:
    build: auth-service
    container_name: auth-service
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - discovery-server
    ports:
      - "8083:8083"
    expose:
      - "8083"

  api-gateway:
    build: api-gateway
    container_name: api-gateway
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    ports:
      - "8080:8080"
    expose:
      - "8080"
    depends_on:
      - discovery-server

  user_service:
    build: user-service
    container_name: user-service
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    ports:
      - "8081:8081"
    expose:
      - "8081"
    depends_on:
      - api-gateway
      - postgres-user

  credit_service:
    build: credit-service
    container_name: credit-service
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    ports:
      - "8082:8082"
    expose:
      - "8082"
    depends_on:
      - api-gateway
      - postgres-credit