version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: user-service-postgres
    environment:
      POSTGRES_DB: user_service_db
      POSTGRES_USER: userService
      POSTGRES_PASSWORD: userService

  app:
    build: ./
    container_name: user-service
    ports:
      - "8080:8080"